### ISSUE TITLE
Restructure documentation

### ISSUE THREAD

**Issue by juriroemer** [Sciebo-RDS/Sciebo-RDS#135]
- [ ] Create high level quickstart admin manual (push Administration > Kubernetes into main menu).
- [ ] Make `general conception` graphic less confusing

**Comment by juriroemer** [comment]
![IMG_2032](https://user-images.githubusercontent.com/31971585/181753049-7ce85509-e42d-4fde-a0b8-fabcbc5aee58.jpg)

+ Frontend development

**Comment by juriroemer** [comment]
+ Publications

**Comment by Heiss** [comment]
every view needs separate FAQ
user prospect: which functionalities are ready to use

**Comment by juriroemer** [comment]
contributing > translation
