### ISSUE TITLE
[Repositories view] Disconnecting Zenodo disconnects OSF as well

### ISSUE THREAD

**Issue by juriroemer** [Sciebo-RDS/Sciebo-RDS#213]
**To Reproduce**
1. have both Zenodo and OSF connected
2. disconnect Zenodo in the `Repositories` view
3. both Zenodo and OSF get disconnected

**Expected behaviour**
Only Zenodo gets disconnected

Edit: Now that datasafe is also selectable, this happens the other way around

**Comment by juriroemer** [comment]
This seems to be a bigger problem with the token removal in the token storage: https://github.com/Sciebo-RDS/Sciebo-RDS/blob/8baf67be51f4fbe66f42b81d607b5056f7a20982/RDS/layer3_central_services/token_storage/src/lib/Storage.py#L431

**Comment by davetromp** [comment]
Just created this PR that will fix the issue: https://github.com/Sciebo-RDS/Sciebo-RDS/pull/239

**Comment by davetromp** [comment]
As the PR has been merged, can this issue be closed?
