### ISSUE TITLE
Explain or remove "Researchindex"

### ISSUE THREAD

**Issue by borsna** [Sciebo-RDS/Sciebo-RDS#230]
**Is your feature request related to a problem? Please describe.**
To a user its unclear what to do with the information "Researchindex". No context/explanation is given.
If its not needed it should be removed.

![image](https://user-images.githubusercontent.com/794445/214864972-874ac5c7-da9f-47e2-8722-1fe6c740e0fa.png)

**Describe the solution you'd like**
Clarify or remove it.

**Describe alternatives you've considered**
Add it as a hidden data-attribute on the project if its needed for debug-purposes.

**Comment by juriroemer** [comment]
Hey Olof,
The RDS version you're using is very old. The interface has since been completely redesigned, and as a matter of fact will soon be rewritten in vue.js 3 (currently version 2).
The redesign should already fix all the concerns raised in this issue, as well as those in #227, #228, #229!
