### ISSUE TITLE
Buttons linking to external sites do not work in iframe anymore

### ISSUE THREAD

**Issue by davetromp** [Sciebo-RDS/Sciebo-RDS#240]
Since a few weeks the buttons that link to external sites do nothing anymore when clicked.
This is for instance the case for the 'getting started' button and the 'connect' buttons of ports connecting using OAUTH.

# Getting Started Button
![image](https://user-images.githubusercontent.com/2326631/225586636-e9c184ad-be25-41b6-83e1-db8179768437.png)
## Frontend error firefox
![image](https://user-images.githubusercontent.com/2326631/225587046-93f021e2-8031-4432-b2b1-f21916d2889f.png)
## Frontend error Chrome
![image](https://user-images.githubusercontent.com/2326631/225597669-63c214a6-ec9f-48dd-9535-f9aeee4f2df9.png)

I think here we should add 'allow-popups' to the sandbox attribute.
`<iframe id="rds-editor" src="https://rds-rd-app-acc.data.surfsara.nl:443?embed=1&amp;lang=en" sandbox="allow-same-origin allow-scripts" class="uk-height-1-1 uk-width-1-1" style="width: 100%; height: 100%;"></iframe>`

I think this can be done here: RDS/layer0_ingress/web/client/packages/web/src/App.vue or here: RDS/layer0_ingress/web/client/packages/classic/src/App.vue

**Comment by wlohman-surfsara** [comment]
The sandbox settings are defined in /var/www/owncloud/apps/rds/js/app.js
Adding 'allow-popups' there does open a new tab when you click 'getting started' (in both Firefox and Chrome), though I get an oauth redirect issue somewhere along the line

**Comment by davetromp** [comment]
This issue seems to be resolved after updating our application to the latest version of the Sciebo RDS mono repo.

**Comment by juriroemer** [comment]
Thanks - I'll close this issue for now, please reopen if necessary :)
