### ISSUE TITLE
Metadata is None at Ports

### ISSUE THREAD

**Issue by davetromp** [Sciebo-RDS/Sciebo-RDS#243]
It looks like the metadata is not available in the Flask request.

In the logs of the ports I see:
2023-03-27 14:02:52,240 Entering at api/project/project.py post
2023-03-27 14:02:52,240 got metadata: None
2023-03-27 14:02:52,240 send metadata: None

The relevant code is in the file api/project/project.py at the post function:

```
from flask import jsonify, request, g

req = request.get_json(force=True)
metadata = req.get("metadata")

logger.debug(f"got metadata: {metadata}")

```

This is for all the ports I have available. It is also in the case for for example the zenodo port. So the bug was most likely already in that port and not introduced in the new ports.

Result is that the ports work in the sense that files can be uploaded, but metadata will not be uploaded or used.

**Comment by juriroemer** [comment]
@davetromp Please close this issue *in case* yesterday's debug session cleared this up :)

**Comment by davetromp** [comment]
Yes, this issue has been resolved by adjusting the code in the ports. I will be updating the code in the RDS-connectors repo in the coming weeks.
